<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Python Programming: Systematic Sampling

In [71]:
# Importing Numpy
#
import numpy as np
import pandas as pd

## Examples 

In [42]:
# Example 1
# ---
# The idea in systematic sampling is that, given the population units numbered from 1 to  N , 
# we compute for the sampling interval, given by  k=N/n , where  n  is the number of units needed for the sample. 
# After that, we choose for the random start, number between  1  and  k. 
# This random start will be the first sample, and then the second unit in the sample is obtained by adding 
# the sampling interval to the random start, and so on. 
# There are two types of systematic sampling namely, linear and circular systematic samplings. 
# Circular systematic sampling treats the population units numbered from  1  to  N  in circular form,
# so that if the increment step is more than the number of  N  units, say  N+2 , 
# the sample unit is the  2nd element in the population, and so on. 
# The code that we will working with can be used both for linear and circular. 
# Since there are rules in linear that are not satisfied in the function, 
# one of which is if  k  is not a whole number, despite that, however, we can always extend it to a more general function.
# ---
# Question: Perform systematic sampling given the following dataset:
# ---
#

# The data
sal_dat = np.array([25, 15, 20, 25, 18, 12, 24, 30, 15, 20, 10, 10, 11, 14, 22, 16])
salary = sal_dat * 1000

# Function for systematic sampling



def sys_sample(df, r, n):
    k = df.shape[0] // n

    b = [None] * n; a = r
    b[0] = a

    for i in np.arange(1, n):
        a = a + k

        if a > df.shape[0]:
            a = a - df.shape[0]

        b[i] = a

    return {"Data" : df[b], "Index" : b, "K" : k}

# Do the sampling for random start,
# r = 2, and number of sample, n = 4
sys_sample(salary, r = 4, n = 6)

{'Data': array([18000, 24000, 15000, 10000, 11000, 22000]),
 'Index': [4, 6, 8, 10, 12, 14],
 'K': 2}

In [59]:
def systematic_sampling(df,r,n):
    step=df.shape[0]//n
    indexes = np.arange(start=r, stop= len(df), step=step)
    systematic_sample = df[indexes]
    return systematic_sample#, indexes
    
systematic_sampling(salary,4,6)


array([18000, 24000, 15000, 10000, 11000, 22000])

## <font color="green">Challenges</font>

In [51]:
# Challenge 1
# ---
# Question: Peform systematic sampling given the following dataset 
# ---
# Dataset = [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
# Dataset


In [61]:
# Challenge 2
# ---
# Question: You're given data ranging from 175 to 1000. Select a sample from this data by performing systematic sampling.
# ---
# 
numbers = np.arange(175,1000)

systematic_sampling(numbers,100,5)

array([275, 440, 605, 770, 935])

In [68]:
# Challenge 3
# ---
# Question: There are 19 students in this class. Let’s choose a 1-in-3 systematic sample from the 19 students in the class.
# ---
# 
students = np.arange(1,20)
students
systematic_sampling(students,0,7)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [70]:
# Challenge 4
# ---
# Question: Select a sample from n = 12 members from a population of size N = 287. 
# ---
# 
pop = np.arange(1,288)
pop
systematic_sampling(pop,1,12)

array([  2,  25,  48,  71,  94, 117, 140, 163, 186, 209, 232, 255, 278])

In [75]:
# Challenge 5
# ---
# Question: You work for the Olympics Data Analytics in Geneva and would like perform a study on the performance of the top marathon
# olympics athletes. For reasons beyond your control, resort to perform systematic sampling from the given Boston 2017 marathon dataset.
# ---
# Question: http://bit.ly/BostonMarathonDataset
# ---
# 
boston = pd.read_csv('marathon.csv')
boston
#systematic_sampling(boston,0,10)

Unnamed: 0    Bib                      Name  Age M/F           City  \
0               0     11           Kirui, Geoffrey   24   M       Keringet   
1               1     17               Rupp, Galen   30   M       Portland   
2               2     23             Osako, Suguru   25   M   Machida-City   
3               3     21          Biwott, Shadrack   32   M  Mammoth Lakes   
4               4      9            Chebet, Wilson   31   M       Marakwet   
...           ...    ...                       ...  ...  ..            ...   
26405       26405  25166  Steinbach, Paula Eyvonne   61   F        Ontario   
26406       26406  25178        Avelino, Andrew R.   25   M   Fayetteville   
26407       26407  27086           Hantel, Johanna   57   F        Malvern   
26408       26408  25268              Reilly, Bill   64   M       New York   
26409       26409  25266             Rigsby, Scott   48   M     Alpharetta   

      State Country Citizen Unnamed: 9  ...      25K      30K      35K  \
0       NaN     KEN     NaN        NaN  ...  1:16:59  1:33:01  1:48:19   
1        OR     USA     NaN        NaN  ...  1:16:59  1:33:01  1:48:19   
2       NaN     JPN     NaN        NaN  ...  1:17:00  1:33:01  1:48:31   
3        CA     USA     NaN        NaN  ...  1:17:00  1:33:01  1:48:58   
4       NaN     KEN     NaN        NaN  ...  1:16:59  1:33:01  1:48:41   
...     ...     ...     ...        ...  ...      ...      ...      ...   
26405    CA     USA     NaN         MI  ...  4:12:06  5:03:08  5:55:18   
26406    NC     USA     NaN         MI  ...  3:50:19  4:50:01  5:53:48   
26407    PA     USA     NaN        NaN  ...  4:15:21  5:06:37  6:00:33   
26408    NY     USA     NaN         MI  ...  4:06:10  5:07:09  6:06:07   
26409    GA     USA     NaN         MI  ...  4:27:14  5:37:13  6:39:07   

           40K     Pace Proj Time Official Time Overall Gender Division  
0      2:02:53  0:04:57         -       2:09:37       1      1        1  
1      2:03:14  0:04:58         -       2:09:58       2      2        2  
2      2:03:38  0:04:59         -       2:10:28       3      3        3  
3      2:04:35  0:05:03         -       2:12:08       4      4        4  
4      2:05:00  0:05:04         -       2:12:35       5      5        5  
...        ...      ...       ...           ...     ...    ...      ...  
26405  6:46:57  0:16:24         -       7:09:39   26407  11972      344  
26406  6:54:21  0:16:40         -       7:16:59   26408  14436     4774  
26407  6:54:38  0:16:47         -       7:19:37   26409  11973      698  
26408  6:56:08  0:16:49         -       7:20:44   26410  14437     1043  
26409  7:41:23  0:18:15         -       7:58:14   26411  14438     2553  

[26410 rows x 25 columns]